### ISSUE TITLE
scc can't produce the report 

### ISSUE THREAD

**Issue by stepango** [boyter/scc#136]
**Describe the bug**
```
❯ scc
ERROR 2019-11-11T10:24:29Z: failed to read gundam: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read history: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open food: open food: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open deliveries-standard-source: open deliveries-standard-source: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read onboarding-uitoolkit: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open hellfire-kit-implementation: open hellfire-kit-implementation: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-deeplink: open grab-deeplink: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open fragment-coupler: open fragment-coupler: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-omprengan: open grab-omprengan: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open component-ui-tests-kit: open component-ui-tests-kit: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read in-app-notification: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-express-history-bridge: open grab-express-history-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open appstart: open appstart: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-sos: open grab-sos: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open message-center-bridge: open message-center-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-leanplum-notification: open grab-leanplum-notification: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-express-api: open grab-express-api: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open buildSrc: open buildSrc: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-driver-api: open grab-driver-api: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-food-testkit: open grab-food-testkit: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-rides-shared: open grab-rides-shared: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-webview: open grab-webview: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-permissions-controller: open grab-permissions-controller: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open geo/saved-places-bridge: open geo/saved-places-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read geo/poi-selection: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-pois-api: open grab-pois-api: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open payments-components: open payments-components: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read geo/geo-trackers: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-user-bridge: open grab-user-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-preferences-bridge: open grab-preferences-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open auth: open auth: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open security: open security: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-feedback: open grab-feedback: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read trustedpassenger/src/main/java/com/grab/pax/trustedpax: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-user/src/main/java/com/grab/pax/grab_user/model: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open trustedpassenger/src/main/res/values-zh: open trustedpassenger/src/main/res/values-zh: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open trustedpassenger/src/main/res/values-th: open trustedpassenger/src/main/res/values-th: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read trustedpassenger/src/main/res/values-sw360dp: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read trustedpassenger/src/main/res/values: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read trustedpassenger/src/main/res/layout: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open subscription: open subscription: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-food-ride-widgets: open grab-food-ride-widgets: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open trustedpassenger/src/main/res/drawable: open trustedpassenger/src/main/res/drawable: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read base/extensible-lifecycle/src/main/java: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-rent/src: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open left-menu: open left-menu: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-cancellation-tiers-bridge: open grab-cancellation-tiers-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-user/src/test: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open docs: open docs: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-now/src/main/res: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-bottom-navigation-bar/src/test/java: open grab-bottom-navigation-bar/src/test/java: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read ride-widget: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open widget_bridge: open widget_bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read payments: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open pax-plugins: open pax-plugins: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-feature: open grab-feature: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read inbox-bridge: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open loki: open loki: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-unplanned-stops: open grab-unplanned-stops: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open promo-bridge: open promo-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-express-home: open grab-express-home: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open biometrics-kit: open biometrics-kit: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open home: open home: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-location: open grab-location: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open food-theme: open food-theme: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-arrears: open grab-arrears: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read biometrics-kit-impl: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open beta: open beta: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open reward-membership: open reward-membership: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read hitch-utils: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open food-screen: open food-screen: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open language-toggle: open language-toggle: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open category-tile: open category-tile: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-empathy: open grab-empathy: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open bottomtab: open bottomtab: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open shared-plugin-view: open shared-plugin-view: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-pay-later-bridge/src: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open platform: open platform: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open hedwig-notification: open hedwig-notification: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read bookingcore-utils/src/main/java: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-leanplum: open grab-leanplum: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-express/src/main/res/drawable-xxxhdpi: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-express/src/main/res/values-id: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-selfie/src/main: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-express/src/main/res/drawable-mdpi: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-express/src/main/res/values-th: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-pay-later/src: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-selfie/src/test/java: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read base/grab-datalinkers/src/main/java/com/grab/pax: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read base/grab-response-mapper/src/main/java: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-express/src/main/res/animator: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-express/src/main/res/values: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-express/src/main/res/values-km: open grab-express/src/main/res/values-km: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open scripts: open scripts: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-express/src/main/res/color: open grab-express/src/main/res/color: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-express/src/main/res/values-ms: open grab-express/src/main/res/values-ms: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grabmall: open grabmall: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read login-register/src: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open media-kit-implementation/src/main/res: open media-kit-implementation/src/main/res: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open digitalfortress: open digitalfortress: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read media-kit-implementation/src/main/java: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read payments-campaigns/src/test/java/com/grab: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read zxing-grab-embedded/src/com/journeyapps/barcodescanner/camera: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open inbox/src/test/java/com/grab/inbox/network: open inbox/src/test/java/com/grab/inbox/network: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open login_register_bridge/src/main/java/com/grab/loginregister/repositories: open login_register_bridge/src/main/java/com/grab/loginregister/repositories: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-messages: open grab-messages: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read base/grab-ride-state/src/main/java/com/grab/rewards: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-style/src/main/res: open grab-style/src/main/res: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open ride-map-controller: open ride-map-controller: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open base/grab-ride-state/src/main/java/com/grab/pax/di: open base/grab-ride-state/src/main/java/com/grab/pax/di: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-express/src/test/java/com/grab/express/prebooking: open grab-express/src/test/java/com/grab/express/prebooking: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-express/src/test/java/com/grab/express/api: open grab-express/src/test/java/com/grab/express/api: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-express/src/test/java/com/grab/express/model: open grab-express/src/test/java/com/grab/express/model: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read rewards-bridge/src/test/java: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read geo/base-data: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-promo: open grab-promo: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-profile: open grab-profile: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-food-datasource-provider/src/main/java/com/grab/pax/grabmall/model: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open lightstep-tracer/src/main: open lightstep-tracer/src/main: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-food-gallery: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open geo/route-api: open geo/route-api: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open geo/route: open geo/route: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open geo/saved-places: open geo/saved-places: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read rewards-bridge/src/main/java/com: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-help-center/src/test/java/com/grab/pax/analytics: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open geo/GeoPIP4J: open geo/GeoPIP4J: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open payments-campaigns/src/main/res/values-vi: open payments-campaigns/src/main/res/values-vi: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read payments-campaigns/src/main/res/values: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read payments-campaigns/src/main/res/values-ms: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read payments-campaigns/src/main/res/layout: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read geo/in-transit-map: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open payments-campaigns/src/main/res/drawable-v24: open payments-campaigns/src/main/res/drawable-v24: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-sdk/src/main/res/values-th: open grab-sdk/src/main/res/values-th: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-sdk/src/main/res/values-vi: open grab-sdk/src/main/res/values-vi: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-sdk/src/main/res/values: open grab-sdk/src/main/res/values: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-sdk/src/main/res/values-ms: open grab-sdk/src/main/res/values-ms: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-sdk/src/main/res/layout: open grab-sdk/src/main/res/layout: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-sdk/src/main/res/values-in: open grab-sdk/src/main/res/values-in: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-sdk/src/main/res/drawable: open grab-sdk/src/main/res/drawable: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read universal-search: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-express/src/test/java/com/grab/express/booking/utils: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-scribe-sdk: open grab-scribe-sdk: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-express/src/test/java/com/grab/express/booking/rides: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-express/src/test/java/com/grab/express/booking/allocating: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open lastadapter: open lastadapter: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-utils/src/main/java/com/grab/pax/navigation: open grab-utils/src/main/java/com/grab/pax/navigation: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-utils/src/main/java/com/grab/pax/controller: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read remittance-bridge/src: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open food-uc: open food-uc: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open newface/src/main: open newface/src/main: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open food-data: open food-data: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open kyc: open kyc: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open app: open app: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-devices: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-api/src/main/java/com/grab/pax/api/model: open grab-api/src/main/java/com/grab/pax/api/model: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-api/src/main/java/com/grab/pax/api/tipping: open grab-api/src/main/java/com/grab/pax/api/tipping: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read remittance: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-api/src/main/java/com/grab/pax/api/utils: open grab-api/src/main/java/com/grab/pax/api/utils: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-api/src/main/java/com/grab/pax/api/v2: open grab-api/src/main/java/com/grab/pax/api/v2: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-api/src/main/java/com/grab/pax/api/deserializers: open grab-api/src/main/java/com/grab/pax/api/deserializers: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read enterprise/business-profile-bridge: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-api/src/main/java/com/grab/pax/api/v1: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read shared-scheduler-provider: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-farealert/src/main: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-tracer/src/main/java: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open enterprise/business-profile: open enterprise/business-profile: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-bus-api: open grab-bus-api: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-urls: open grab-urls: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-farealert/src/test: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-food: open grab-food: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open app-start-log: open app-start-log: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-cancellation-tiers: open grab-cancellation-tiers: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open payments-sdk: open payments-sdk: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-gcm: open grab-gcm: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-bus: open grab-bus: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read transport: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open di: open di: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open newface-common: open newface-common: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-experimentation: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open pin-common: open pin-common: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open feature-toggle: open feature-toggle: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open pending-ride: open pending-ride: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open offers_kit: open offers_kit: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read hitch/src: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open chat-kit: open chat-kit: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read docker: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open sandbox: open sandbox: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open react-native-src: open react-native-src: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read common-rides: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open .mainframer: open .mainframer: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-authorise-extension: open grab-authorise-extension: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open newface-native-feed: open newface-native-feed: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-tooltips: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-bottom-navigation-bar/src/main: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read inbox/src/main: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read zxing-grab-embedded/src/com/grab/zxing/client/android/camera: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read trustedpassenger/src/main/res/values-vi: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open subscription-bridge: open subscription-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open gradle: open gradle: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-happyfresh/src: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read trustedpassenger/src/main/res/values-in: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-pois: open grab-pois: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-rides-api: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read activity-base: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open .android: open .android: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open jacoco: open jacoco: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-now/src/main/java: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open payment-campaigns-bridge: open payment-campaigns-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-business: open grab-business: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read food-global: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-early-access: open grab-early-access: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read rtc-experimentation: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-safetycenter: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-messages-bridge: open grab-messages-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open network-kit-retrofit: open network-kit-retrofit: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open onboarding_bridge: open onboarding_bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open history-bridge: open history-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open payment-kit-bridge: open payment-kit-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-tis: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-wheels: open grab-wheels: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open fulfillment: open fulfillment: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open subscription_kit_bridge: open subscription_kit_bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-business-bridge: open grab-business-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-express/src/main/res/layout: open grab-express/src/main/res/layout: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-express/src/main/res/values-in: open grab-express/src/main/res/values-in: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read threatmetrix: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-express/src/main/res/drawable: open grab-express/src/main/res/drawable: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-express-notification: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read media-kit-implementation/src/test/java/com/grab/media/kit/implementation/utils: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-booking-details: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-partner: open grab-partner: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open help-center-navigator: open help-center-navigator: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read message-center: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grabmall-screens/grabmall-screen-confirm/src: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read buildsystem: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open ovo-sdk-bridge: open ovo-sdk-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open rewards: open rewards: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read payment-kit-implementation/src: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-express-kit: open grab-express-kit: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read network-kit-test: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open testlibs: open testlibs: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open transport-history: open transport-history: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-splash/src/main/java: open grab-splash/src/main/java: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read inbox/src/test/java/com/grab/inbox/ui: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open geo/gms-utils: open geo/gms-utils: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read monitoring/src/main/java/com/grab: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open rewards-kit-bridge: open rewards-kit-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open ci: open ci: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open login_register_bridge/src/main/res: open login_register_bridge/src/main/res: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read category-tile-web: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-splash/src/main/res: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open on-boarding: open on-boarding: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read login_register_bridge/src/test: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-user-api/src/test: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-style/src/main/java: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-express/src/test/java/com/grab/express/pushnotification: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open geo/legacy-poi-search: open geo/legacy-poi-search: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open payment-bridge: open payment-bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open offers_kit_implementation: open offers_kit_implementation: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open ovo-sdk: open ovo-sdk: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open shared-transport-ride-models: open shared-transport-ride-models: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open grab-food-datasource-provider/src/main/java/com/grab/pax/grabmall/bridge: open grab-food-datasource-provider/src/main/java/com/grab/pax/grabmall/bridge: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open geo/feature-flags: open geo/feature-flags: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open geo/nolo: open geo/nolo: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open geo/geo-prebooking: open geo/geo-prebooking: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open geo/geo-analytics: open geo/geo-analytics: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-record/grab-record-kit/src/main/res: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to open geo/poi-search: open geo/poi-search: too many open files
ERROR 2019-11-11T10:24:29Z: failed to read grab-widget/grab-widget-transport-mca/src: fcntl: too many open files
ERROR 2019-11-11T10:24:29Z: failed to load gitignore voip-kit-implementation: open voip-kit-implementation/.gitignore: too many open files
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x116f39d]

goroutine 287 [running]:
github.com/boyter/scc/processor.(*DirectoryWalker).Readdir(0xc0001ca000, 0xc0004f8960)
	/private/tmp/scc-20191021-16987-sub4ir/scc-2.10.0/src/github.com/boyter/scc/processor/file.go:162 +0x5ad
github.com/boyter/scc/vendor/github.com/dbaggerman/cuba.(*Pool).runWorker(0xc0001d6040)
	/private/tmp/scc-20191021-16987-sub4ir/scc-2.10.0/src/github.com/boyter/scc/vendor/github.com/dbaggerman/cuba/pool.go:164 +0x81
created by github.com/boyter/scc/vendor/github.com/dbaggerman/cuba.(*Pool).PushAll
	/private/tmp/scc-20191021-16987-sub4ir/scc-2.10.0/src/github.com/boyter/scc/vendor/github.com/dbaggerman/cuba/pool.go:105 +0xdc
```
**To Reproduce**

1. Tell us how you were using `scc` either as command line or library.
2. If command line please list the arguments. If library please supply code to demonstrate the issue.
3. If the issue is a miscount or some such please link or supply a file which demonstrates the issue.

Just call scc in my current project directory

**Expected behavior**
Expecting to see the report

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 2.10.0

**Comment by boyter** [comment]
Fairly confident that this is the same as https://github.com/boyter/scc/issues/134

@stepango Would you be able to to try this build https://github.com/boyter/scc/files/3829035/scc-2.11.0-x86_64-apple-darwin.zip (also attached to that other ticket) which should resolve the issue for me and report back?

**Comment by boyter** [comment]
@stepango Can confirm this is resolved in the other issue. Suspect that if you try this it will work. If so I will push out a bugfix release.

**Comment by boyter** [comment]
@stepango Can you please either try the above attachment or the latest release 2.10.1 which I believe should resolve this. If not I am going to assume the fix should resolve it for you and close this down in a day or two.

**Comment by boyter** [comment]
No response going to assume the latest fix resolves it. If that's not the case please reopen this and we will investigate.
