### ISSUE TITLE
Slice bounds out of range.

### ISSUE THREAD

**Issue by rgarc** [boyter/scc#149]
**Describe the bug**
```
panic: runtime error: slice bounds out of range [:1] with length 0

goroutine 39 [running]:
github.com/boyter/scc/vendor/github.com/monochromegane/go-gitignore.(*initialPatternHolder).add(0xc0001ecb00, 0x144accf, 0x1)
        /private/tmp/scc-20191112-80174-1mg17yr/scc-2.10.1/src/github.com/boyter/scc/vendor/github.com/monochromegane/go-gitignore/initial_holder.go:21 +0x5ed
github.com/boyter/scc/vendor/github.com/monochromegane/go-gitignore.(*depthPatterns).set(0xc0004d4000, 0x1, 0x144accf, 0x1)
        /private/tmp/scc-20191112-80174-1mg17yr/scc-2.10.1/src/github.com/boyter/scc/vendor/github.com/monochromegane/go-gitignore/depth_holder.go:67 +0xe5
github.com/boyter/scc/vendor/github.com/monochromegane/go-gitignore.(*depthPatternHolder).add(0xc0004d4000, 0x144accf, 0x1)
        /private/tmp/scc-20191112-80174-1mg17yr/scc-2.10.1/src/github.com/boyter/scc/vendor/github.com/monochromegane/go-gitignore/depth_holder.go:24 +0xad
github.com/boyter/scc/vendor/github.com/monochromegane/go-gitignore.(*indexScanPatterns).add(0xc0004d4000, 0x144accf, 0x1)
        /private/tmp/scc-20191112-80174-1mg17yr/scc-2.10.1/src/github.com/boyter/scc/vendor/github.com/monochromegane/go-gitignore/index_scan_patterns.go:19 +0x51
github.com/boyter/scc/vendor/github.com/monochromegane/go-gitignore.NewGitIgnoreFromReader(0xc0003d2310, 0x4, 0x12dafa0, 0xc000264028, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/scc-20191112-80174-1mg17yr/scc-2.10.1/src/github.com/boyter/scc/vendor/github.com/monochromegane/go-gitignore/gitignore.go:54 +0x335
github.com/boyter/scc/vendor/github.com/monochromegane/go-gitignore.NewGitIgnore(0xc0003d2310, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/scc-20191112-80174-1mg17yr/scc-2.10.1/src/github.com/boyter/scc/vendor/github.com/monochromegane/go-gitignore/gitignore.go:35 +0x125
github.com/boyter/scc/processor.(*DirectoryWalker).Walk(0xc0001b2000, 0xc00046c000)
        /private/tmp/scc-20191112-80174-1mg17yr/scc-2.10.1/src/github.com/boyter/scc/processor/file.go:122 +0xa46
github.com/boyter/scc/vendor/github.com/dbaggerman/cuba.(*Pool).runWorker(0xc0001be040)
        /private/tmp/scc-20191112-80174-1mg17yr/scc-2.10.1/src/github.com/boyter/scc/vendor/github.com/dbaggerman/cuba/pool.go:163 +0x72
created by github.com/boyter/scc/vendor/github.com/dbaggerman/cuba.(*Pool).PushAll
        /private/tmp/scc-20191112-80174-1mg17yr/scc-2.10.1/src/github.com/boyter/scc/vendor/github.com/dbaggerman/cuba/pool.go:105 +0xe1
```

**To Reproduce**

1. Using as binary downloaded from `$ brew install scc`
2. Clone the [mono repo](https://github.com/mono/mono) and run `scc` in the root of the repo.
3. It crashes and produces the message above.

**Expected behavior**
Shouldn't crash.

**Desktop (please complete the following information):**
 Ubuntu 18.04 and macOS Catalina version 10.15.2

**Comment by dbaggerman** [comment]
I can reproduce this. Appears to be a bug/issue with the `monochromegane/go-gitignore` dependency.

Some of the `.gitignore` files in the `mono` repo have lines containing simply `/`. It looks like `go-gitignore` tries to trim leading `/`s, which turns these into empty lines. It then assumes it can slice into the empty string, which causes the panic.

We can try raising an issue with them, but given that it hasn't had any activity in the last four years I'm not going to hold my breath for a fix. Maybe there are other libraries we can look at as a replacement for `monochromegane/go-gitignore`.

**Comment by boyter** [comment]
Can also reproduce. Annoying. Have raised the issue over there https://github.com/monochromegane/go-gitignore/issues/5

I had a look previously for another library and I couldn't find one. Id like there to be something as accurate as the one used in Rust. Id create it myself but I am not familiar enough with how .gitignore files to actually do it.

For the moment I am going to patch the vendor dependency to prevent the crash like so,

```
func (h *initialPatternHolder) add(pattern string) {
	trimedPattern := strings.TrimPrefix(pattern, "/")

	// https://github.com/boyter/scc/issues/149
	if trimedPattern == "" {
		return
	}

	if strings.IndexAny(trimedPattern[0:1], initials) != -1 {
		h.patterns.set(trimedPattern[0], newPatternForEqualizedPath(pattern))
	} else {
		h.otherPatterns.add(newPatternForEqualizedPath(pattern))
	}
}
``` 

and roll it into the next release.
