### ISSUE TITLE
Panic in codeState

### ISSUE THREAD

**Issue by fiorix** [boyter/scc#172]
Getting this panic running `scc -f json --by-file /path`:

```
panic: runtime error: index out of range [116] with length 116
goroutine 239 [running]:
github.com/boyter/scc/processor.codeState(0xc03a1e2b60, 0x1, 0x84, 0x2, 0xc002427348, 0x0, 0x0, 0xc002427348, 0x0, 0x0, ...)
	github.com/boyter/scc/processor/workers.go:195 +0x73c
github.com/boyter/scc/processor.CountStats(0xc03a1e2b60)
	github.com/boyter/scc/processor/workers.go:432 +0xdca
github.com/boyter/scc/processor.processFile(0xc03a1e2b60, 0xc03331e660)
	github.com/boyter/scc/processor/workers.go:708 +0x27c
github.com/boyter/scc/processor.fileProcessorWorker.func1(0xc0000ec5a0, 0xc0002003d0, 0xc0002003d8, 0xc0002003e0, 0xc0000ec600, 0xc0002003f0)
	github.com/boyter/scc/processor/workers.go:649 +0x284
created by github.com/boyter/scc/processor.fileProcessorWorker
	github.com/boyter/scc/processor/workers.go:625 +0xfb
```

**Comment by gallois** [comment]
I've talked to @fiorix about this issue and it seems to be related to not following symlinks. I'm working on fixing it for myself and I'll send a PR for it soon.

**Comment by boyter** [comment]
Thanks so much for reporting and the PR!

**Comment by fiorix** [comment]
Thanks for the quick review and merge
