### ISSUE TITLE
panic: runtime error: index out of range [27] with length 27

### ISSUE THREAD

**Issue by ostrolucky** [boyter/scc#192]
```
❯ scc                                                                                                 8s
panic: runtime error: index out of range [27] with length 27

goroutine 53 [running]:
github.com/boyter/scc/processor.codeState(0xc013ec15e0, 0x1, 0x1e, 0x2, 0xc008881348, 0x0, 0x0, 0xc008881348, 0x0, 0x0, ...)
	/private/tmp/scc-20200303-52931-1xbax9l/scc-2.12.0/src/github.com/boyter/scc/processor/workers.go:194 +0x730
github.com/boyter/scc/processor.CountStats(0xc013ec15e0)
	/private/tmp/scc-20200303-52931-1xbax9l/scc-2.12.0/src/github.com/boyter/scc/processor/workers.go:431 +0xdca
github.com/boyter/scc/processor.processFile(0xc013ec15e0, 0xc013ec4300)
	/private/tmp/scc-20200303-52931-1xbax9l/scc-2.12.0/src/github.com/boyter/scc/processor/workers.go:707 +0x27c
github.com/boyter/scc/processor.fileProcessorWorker.func1(0xc000210360, 0xc00008e000, 0xc00008e008, 0xc00008e010, 0xc000210420, 0xc00008e020)
	/private/tmp/scc-20200303-52931-1xbax9l/scc-2.12.0/src/github.com/boyter/scc/processor/workers.go:648 +0x284
created by github.com/boyter/scc/processor.fileProcessorWorker
	/private/tmp/scc-20200303-52931-1xbax9l/scc-2.12.0/src/github.com/boyter/scc/processor/workers.go:624 +0xfb
```

**Desktop (please complete the following information):**
 - OS: MacOs Catalina 
 - Version 10.15.6 

scc version 2.12.0

**Comment by boyter** [comment]
@ostrolucky Would it be possible for you to try the lastest build from master? I suspect this might be a symlink issue which should hopefully be resolved.

**Comment by ostrolucky** [comment]
Yep, that solved the issue

**Comment by boyter** [comment]
Confirmed symlink issue then. Great.
