### ISSUE TITLE
SIGSEGV if specifying a non-existent file under a file

### ISSUE THREAD

**Issue by starpit** [boyter/scc#563]
**Describe the bug**

I ran into this due to user error: if you point `scc` to a file under a file (e.g. if `foo` is a file and you run `scc foo/bar`) you get a segfault.

**To Reproduce**

```shell
$ touch /tmp/foo
$ scc /tmp/foo/bar
scc /tmp/foo/bar
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x102489fc0]

goroutine 1 [running]:
github.com/boyter/scc/v3/processor.Process()
	github.com/boyter/scc/v3/processor/processor.go:586 +0x220
main.main.func1(0x14000104400?, {0x14000092b20?, 0x7?, 0x1024fb9ce?})
	github.com/boyter/scc/v3/main.go:49 +0x98
github.com/spf13/cobra.(*Command).execute(0x1400010c008, {0x140000ba010, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.1/command.go:989 +0x81c
github.co
m/spf13/cobra.(*Command).ExecuteC(0x1400010c008)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
main.main()
	github.com/boyter/scc/v3/main.go:401 +0xeec
```
**Expected behavior**
I guess fail fast and gracefully?

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 15.1.1
 - scc Version: 3.4.0

**Comment by boyter** [comment]
Oddly I am unable to replicate this...

```
# boyter @ macbookair in / [17:45:18] 
$ touch /tmp/foo

# boyter @ macbookair in / [17:45:21] 
$ scc /tmp/foo/bar
file or directory could not be read: /tmp/foo/bar
```

Is there some other thing you did?

**Comment by starpit** [comment]
Nice. I just built from the main branch, and this problem seems to have been fixed.

Thank you for this work. Much appreciated.

**Comment by boyter** [comment]
Thanks for confirming for me!
